service:
  name: product-page-svc
  port: 9080

productionDeployment:
  replicaCount: 2
  weight: 100
  image:
    repository: istioacr.azurecr.io/istiosample/productpage
    tag: 72
    pullPolicy: IfNotPresent


canaryDeployment:
  replicaCount: 0
  weight: 0
  image:
    repository: istioacr.azurecr.io/istiosample/productpage
    tag: 72
    pullPolicy: IfNotPresent



